import { Country, Page, Slot, SlotType, Marketplace } from "./types";

export const countries: Country[] = [
  { code: "AE", name: "United Arab Emirates", flag: "🇦🇪", currency: "AED", timezone: "Asia/Dubai" },
  { code: "SA", name: "Saudi Arabia", flag: "🇸🇦", currency: "SAR", timezone: "Asia/Riyadh" },
  { code: "EG", name: "Egypt", flag: "🇪🇬", currency: "EGP", timezone: "Africa/Cairo" },
];

export const marketplaces: { id: Marketplace; name: string; icon: string }[] = [
  { id: "noon", name: "noon", icon: "🟡" },
  { id: "supermall", name: "Supermall", icon: "🛒" },
];

export const pages: Page[] = [
  // Core Pages
  { id: "homepage", name: "Homepage", description: "Main landing page" },
  { id: "search", name: "Search Page", description: "Search results page" },
  { id: "pdp", name: "Product Detail Page", description: "Individual product pages" },
  { id: "cart", name: "Cart Page", description: "Shopping cart page" },
  { id: "checkout", name: "Checkout Page", description: "Checkout flow" },
  // Electronics CLPs
  { id: "electronics_clp", name: "Electronics", description: "Electronics category page" },
  { id: "mobiles_clp", name: "Mobiles & Tablets", description: "Mobiles & Tablets category page" },
  { id: "laptops_clp", name: "Laptops & Computers", description: "Laptops & Computers category page" },
  { id: "tv_clp", name: "TV & Home Entertainment", description: "TV & Audio category page" },
  { id: "gaming_clp", name: "Gaming & Consoles", description: "Gaming category page" },
  { id: "cameras_clp", name: "Cameras & Photography", description: "Cameras category page" },
  { id: "wearables_clp", name: "Wearables & Smartwatches", description: "Wearables category page" },
  // Fashion CLPs
  { id: "fashion_clp", name: "Fashion", description: "Fashion category page" },
  { id: "men_fashion_clp", name: "Men's Fashion", description: "Men's fashion category page" },
  { id: "women_fashion_clp", name: "Women's Fashion", description: "Women's fashion category page" },
  { id: "kids_fashion_clp", name: "Kids Fashion", description: "Kids fashion category page" },
  { id: "shoes_clp", name: "Shoes & Footwear", description: "Footwear category page" },
  { id: "watches_clp", name: "Watches", description: "Watches category page" },
  { id: "jewelry_clp", name: "Jewelry", description: "Jewelry category page" },
  { id: "eyewear_clp", name: "Eyewear", description: "Eyewear category page" },
  // Beauty & Personal Care CLPs
  { id: "beauty_clp", name: "Beauty", description: "Beauty category page" },
  { id: "skincare_clp", name: "Skincare", description: "Skincare category page" },
  { id: "makeup_clp", name: "Makeup", description: "Makeup category page" },
  { id: "fragrance_clp", name: "Fragrances", description: "Perfumes category page" },
  { id: "haircare_clp", name: "Haircare", description: "Haircare category page" },
  { id: "grooming_clp", name: "Men's Grooming", description: "Men's grooming category page" },
  // Home & Living CLPs
  { id: "home_clp", name: "Home & Kitchen", description: "Home & Kitchen category page" },
  { id: "furniture_clp", name: "Furniture", description: "Furniture category page" },
  { id: "kitchen_clp", name: "Kitchen Appliances", description: "Kitchen appliances category page" },
  { id: "home_decor_clp", name: "Home Decor", description: "Home decor category page" },
  { id: "bedding_clp", name: "Bedding & Bath", description: "Bedding category page" },
  { id: "garden_clp", name: "Garden & Outdoor", description: "Garden category page" },
  // Baby & Kids CLPs
  { id: "babies_clp", name: "Babies & Toys", description: "Babies & Toys category page" },
  { id: "toys_clp", name: "Toys & Games", description: "Toys category page" },
  { id: "baby_gear_clp", name: "Baby Gear", description: "Strollers & car seats category page" },
  { id: "baby_care_clp", name: "Baby Care", description: "Baby care products category page" },
  // Sports & Outdoors CLPs
  { id: "sports_clp", name: "Sports & Outdoors", description: "Sports & Outdoors category page" },
  { id: "fitness_clp", name: "Fitness & Exercise", description: "Fitness equipment category page" },
  { id: "outdoor_clp", name: "Outdoor Recreation", description: "Camping & outdoor gear category page" },
  { id: "cycling_clp", name: "Cycling", description: "Bikes & cycling category page" },
  // Grocery & Essentials CLPs
  { id: "grocery_clp", name: "Grocery", description: "Grocery category page" },
  { id: "beverages_clp", name: "Beverages", description: "Drinks category page" },
  { id: "snacks_clp", name: "Snacks & Confectionery", description: "Snacks category page" },
  { id: "household_clp", name: "Household Essentials", description: "Cleaning & household category page" },
  { id: "pet_supplies_clp", name: "Pet Supplies", description: "Pet food & supplies category page" },
  // Other CLPs
  { id: "automotive_clp", name: "Automotive", description: "Car accessories category page" },
  { id: "books_clp", name: "Books & Media", description: "Books category page" },
  { id: "office_clp", name: "Office Supplies", description: "Office supplies category page" },
  { id: "health_clp", name: "Health & Wellness", description: "Health products category page" },
];

// Slot dimensions by type and country
// Mobile hero: 706x320 (all regions)
// Mobile slim: 800x200 (all regions)
// Desktop hero: 1008x200 (UAE/KSA), 1440x200 (EGY)
// Desktop slim: 1440x200 (all regions)

// Helper function to generate individual slots for a CLP page
// For CPT: Individual slots (Hero Banner 1, Hero Banner 2, etc.)
// For CPM: These get grouped into zones in the UI
const generateCLPSlots = (pageId: string, pageName: string, baseViews: number, baseRate: number): Slot[] => [
  // Hero Banner slots (2 per page)
  {
    id: `${pageId}_hero_1`,
    name: "Hero Banner 1",
    zone: "Hero Banners",
    pageId,
    slotType: "mobile_hero" as SlotType,
    dimensions: "706x320",
    dimensionsByCountry: { AE: "1008x200", SA: "1008x200", EG: "1440x200" },
    position: "Above fold",
    avgDailyViews: Math.round(baseViews * 0.6),
    cptRateUsd: baseRate,
    minCpmUsd: Math.round(baseRate * 0.15),
    supportedFormats: ["image/png", "image/jpeg", "image/gif"],
    maxFileSizeMb: 2,
    viewsPerDay: Math.round(baseViews * 0.6),
  },
  {
    id: `${pageId}_hero_2`,
    name: "Hero Banner 2",
    zone: "Hero Banners",
    pageId,
    slotType: "mobile_hero" as SlotType,
    dimensions: "706x320",
    dimensionsByCountry: { AE: "1008x200", SA: "1008x200", EG: "1440x200" },
    position: "Above fold",
    avgDailyViews: Math.round(baseViews * 0.4),
    cptRateUsd: Math.round(baseRate * 0.85),
    minCpmUsd: Math.round(baseRate * 0.12),
    supportedFormats: ["image/png", "image/jpeg", "image/gif"],
    maxFileSizeMb: 2,
    viewsPerDay: Math.round(baseViews * 0.4),
  },
  // Top Fold slots (2 per page)
  {
    id: `${pageId}_top_fold_1`,
    name: "Top Fold Unit 1",
    zone: "Top Fold Units",
    pageId,
    slotType: "mobile_slim" as SlotType,
    dimensions: "800x200",
    position: "Below hero",
    avgDailyViews: Math.round(baseViews * 0.5),
    cptRateUsd: Math.round(baseRate * 0.7),
    minCpmUsd: Math.round(baseRate * 0.12),
    supportedFormats: ["image/png", "image/jpeg", "image/gif"],
    maxFileSizeMb: 2,
    viewsPerDay: Math.round(baseViews * 0.5),
  },
  {
    id: `${pageId}_top_fold_2`,
    name: "Top Fold Unit 2",
    zone: "Top Fold Units",
    pageId,
    slotType: "mobile_slim" as SlotType,
    dimensions: "800x200",
    position: "Below hero",
    avgDailyViews: Math.round(baseViews * 0.3),
    cptRateUsd: Math.round(baseRate * 0.6),
    minCpmUsd: Math.round(baseRate * 0.1),
    supportedFormats: ["image/png", "image/jpeg", "image/gif"],
    maxFileSizeMb: 2,
    viewsPerDay: Math.round(baseViews * 0.3),
  },
  // Second Fold slots (2 per page)
  {
    id: `${pageId}_second_fold_1`,
    name: "Second Fold Unit 1",
    zone: "Second Fold Units",
    pageId,
    slotType: "desktop_slim" as SlotType,
    dimensions: "1440x200",
    position: "Mid scroll",
    avgDailyViews: Math.round(baseViews * 0.3),
    cptRateUsd: Math.round(baseRate * 0.5),
    minCpmUsd: Math.round(baseRate * 0.1),
    supportedFormats: ["image/png", "image/jpeg", "image/gif"],
    maxFileSizeMb: 3,
    viewsPerDay: Math.round(baseViews * 0.3),
  },
  {
    id: `${pageId}_second_fold_2`,
    name: "Second Fold Unit 2",
    zone: "Second Fold Units",
    pageId,
    slotType: "desktop_slim" as SlotType,
    dimensions: "1440x200",
    position: "Mid scroll",
    avgDailyViews: Math.round(baseViews * 0.2),
    cptRateUsd: Math.round(baseRate * 0.4),
    minCpmUsd: Math.round(baseRate * 0.08),
    supportedFormats: ["image/png", "image/jpeg", "image/gif"],
    maxFileSizeMb: 3,
    viewsPerDay: Math.round(baseViews * 0.2),
  },
];

export const slots: Slot[] = [
  // Homepage Slots - Individual slots for CPT
  {
    id: "hp_hero_1",
    name: "Hero Banner 1",
    zone: "Hero Banners",
    pageId: "homepage",
    slotType: "mobile_hero" as SlotType,
    dimensions: "706x320",
    dimensionsByCountry: { AE: "1008x200", SA: "1008x200", EG: "1440x200" },
    position: "Above fold",
    avgDailyViews: 1500000,
    cptRateUsd: 200,
    minCpmUsd: 25,
    supportedFormats: ["image/png", "image/jpeg", "image/gif"],
    maxFileSizeMb: 2,
    viewsPerDay: 1500000,
  },
  {
    id: "hp_hero_2",
    name: "Hero Banner 2",
    zone: "Hero Banners",
    pageId: "homepage",
    slotType: "mobile_hero" as SlotType,
    dimensions: "706x320",
    dimensionsByCountry: { AE: "1008x200", SA: "1008x200", EG: "1440x200" },
    position: "Above fold",
    avgDailyViews: 1000000,
    cptRateUsd: 170,
    minCpmUsd: 22,
    supportedFormats: ["image/png", "image/jpeg", "image/gif"],
    maxFileSizeMb: 2,
    viewsPerDay: 1000000,
  },
  {
    id: "hp_top_fold_1",
    name: "Top Fold Unit 1",
    zone: "Top Fold Units",
    pageId: "homepage",
    slotType: "mobile_slim" as SlotType,
    dimensions: "800x200",
    position: "Below hero",
    avgDailyViews: 1300000,
    cptRateUsd: 150,
    minCpmUsd: 20,
    supportedFormats: ["image/png", "image/jpeg", "image/gif"],
    maxFileSizeMb: 2,
    viewsPerDay: 1300000,
  },
  {
    id: "hp_top_fold_2",
    name: "Top Fold Unit 2",
    zone: "Top Fold Units",
    pageId: "homepage",
    slotType: "mobile_slim" as SlotType,
    dimensions: "800x200",
    position: "Below hero",
    avgDailyViews: 900000,
    cptRateUsd: 120,
    minCpmUsd: 18,
    supportedFormats: ["image/png", "image/jpeg", "image/gif"],
    maxFileSizeMb: 2,
    viewsPerDay: 900000,
  },
  {
    id: "hp_second_fold_1",
    name: "Second Fold Unit 1",
    zone: "Second Fold Units",
    pageId: "homepage",
    slotType: "desktop_slim" as SlotType,
    dimensions: "1440x200",
    position: "Mid scroll",
    avgDailyViews: 700000,
    cptRateUsd: 100,
    minCpmUsd: 15,
    supportedFormats: ["image/png", "image/jpeg", "image/gif"],
    maxFileSizeMb: 3,
    viewsPerDay: 700000,
  },
  {
    id: "hp_second_fold_2",
    name: "Second Fold Unit 2",
    zone: "Second Fold Units",
    pageId: "homepage",
    slotType: "desktop_slim" as SlotType,
    dimensions: "1440x200",
    position: "Mid scroll",
    avgDailyViews: 500000,
    cptRateUsd: 80,
    minCpmUsd: 12,
    supportedFormats: ["image/png", "image/jpeg", "image/gif"],
    maxFileSizeMb: 3,
    viewsPerDay: 500000,
  },
  // Search Page Slots - Individual slots for CPT
  {
    id: "search_hero_1",
    name: "Hero Banner 1",
    zone: "Hero Banners",
    pageId: "search",
    slotType: "mobile_hero" as SlotType,
    dimensions: "706x320",
    dimensionsByCountry: { AE: "1008x200", SA: "1008x200", EG: "1440x200" },
    position: "Above results",
    avgDailyViews: 900000,
    cptRateUsd: 150,
    minCpmUsd: 20,
    supportedFormats: ["image/png", "image/jpeg", "image/gif"],
    maxFileSizeMb: 2,
    viewsPerDay: 900000,
  },
  {
    id: "search_hero_2",
    name: "Hero Banner 2",
    zone: "Hero Banners",
    pageId: "search",
    slotType: "mobile_hero" as SlotType,
    dimensions: "706x320",
    dimensionsByCountry: { AE: "1008x200", SA: "1008x200", EG: "1440x200" },
    position: "Above results",
    avgDailyViews: 600000,
    cptRateUsd: 125,
    minCpmUsd: 18,
    supportedFormats: ["image/png", "image/jpeg", "image/gif"],
    maxFileSizeMb: 2,
    viewsPerDay: 600000,
  },
  {
    id: "search_top_fold_1",
    name: "Top Fold Unit 1",
    zone: "Top Fold Units",
    pageId: "search",
    slotType: "mobile_slim" as SlotType,
    dimensions: "800x200",
    position: "Below search bar",
    avgDailyViews: 700000,
    cptRateUsd: 120,
    minCpmUsd: 18,
    supportedFormats: ["image/png", "image/jpeg", "image/gif"],
    maxFileSizeMb: 2,
    viewsPerDay: 700000,
  },
  {
    id: "search_top_fold_2",
    name: "Top Fold Unit 2",
    zone: "Top Fold Units",
    pageId: "search",
    slotType: "mobile_slim" as SlotType,
    dimensions: "800x200",
    position: "Below search bar",
    avgDailyViews: 500000,
    cptRateUsd: 100,
    minCpmUsd: 15,
    supportedFormats: ["image/png", "image/jpeg", "image/gif"],
    maxFileSizeMb: 2,
    viewsPerDay: 500000,
  },
  {
    id: "search_second_fold_1",
    name: "Second Fold Unit 1",
    zone: "Second Fold Units",
    pageId: "search",
    slotType: "desktop_slim" as SlotType,
    dimensions: "1440x200",
    position: "Mid results",
    avgDailyViews: 500000,
    cptRateUsd: 100,
    minCpmUsd: 15,
    supportedFormats: ["image/png", "image/jpeg", "image/gif"],
    maxFileSizeMb: 3,
    viewsPerDay: 500000,
  },
  {
    id: "search_second_fold_2",
    name: "Second Fold Unit 2",
    zone: "Second Fold Units",
    pageId: "search",
    slotType: "desktop_slim" as SlotType,
    dimensions: "1440x200",
    position: "Mid results",
    avgDailyViews: 400000,
    cptRateUsd: 80,
    minCpmUsd: 12,
    supportedFormats: ["image/png", "image/jpeg", "image/gif"],
    maxFileSizeMb: 3,
    viewsPerDay: 400000,
  },
  // PDP Slots - Individual slots for CPT
  {
    id: "pdp_hero_1",
    name: "Hero Banner 1",
    zone: "Hero Banners",
    pageId: "pdp",
    slotType: "mobile_hero" as SlotType,
    dimensions: "706x320",
    position: "Above product",
    avgDailyViews: 500000,
    cptRateUsd: 80,
    minCpmUsd: 12,
    supportedFormats: ["image/png", "image/jpeg", "image/gif"],
    maxFileSizeMb: 2,
    viewsPerDay: 500000,
  },
  {
    id: "pdp_hero_2",
    name: "Hero Banner 2",
    zone: "Hero Banners",
    pageId: "pdp",
    slotType: "mobile_hero" as SlotType,
    dimensions: "706x320",
    position: "Above product",
    avgDailyViews: 300000,
    cptRateUsd: 65,
    minCpmUsd: 10,
    supportedFormats: ["image/png", "image/jpeg", "image/gif"],
    maxFileSizeMb: 2,
    viewsPerDay: 300000,
  },
  {
    id: "pdp_second_fold_1",
    name: "Second Fold Unit 1",
    zone: "Second Fold Units",
    pageId: "pdp",
    slotType: "desktop_slim" as SlotType,
    dimensions: "1440x200",
    position: "Below product",
    avgDailyViews: 300000,
    cptRateUsd: 60,
    minCpmUsd: 10,
    supportedFormats: ["image/png", "image/jpeg", "image/gif"],
    maxFileSizeMb: 3,
    viewsPerDay: 300000,
  },
  {
    id: "pdp_second_fold_2",
    name: "Second Fold Unit 2",
    zone: "Second Fold Units",
    pageId: "pdp",
    slotType: "desktop_slim" as SlotType,
    dimensions: "1440x200",
    position: "Below product",
    avgDailyViews: 200000,
    cptRateUsd: 50,
    minCpmUsd: 8,
    supportedFormats: ["image/png", "image/jpeg", "image/gif"],
    maxFileSizeMb: 3,
    viewsPerDay: 200000,
  },
  // Cart & Checkout - Individual slots for CPT
  {
    id: "cart_hero_1",
    name: "Hero Banner 1",
    zone: "Hero Banners",
    pageId: "cart",
    slotType: "mobile_hero" as SlotType,
    dimensions: "706x320",
    position: "Above cart",
    avgDailyViews: 250000,
    cptRateUsd: 60,
    minCpmUsd: 10,
    supportedFormats: ["image/png", "image/jpeg", "image/gif"],
    maxFileSizeMb: 2,
    viewsPerDay: 250000,
  },
  {
    id: "cart_hero_2",
    name: "Hero Banner 2",
    zone: "Hero Banners",
    pageId: "cart",
    slotType: "mobile_hero" as SlotType,
    dimensions: "706x320",
    position: "Above cart",
    avgDailyViews: 150000,
    cptRateUsd: 50,
    minCpmUsd: 8,
    supportedFormats: ["image/png", "image/jpeg", "image/gif"],
    maxFileSizeMb: 2,
    viewsPerDay: 150000,
  },
  // Electronics CLPs
  ...generateCLPSlots("electronics_clp", "Electronics", 800000, 100),
  ...generateCLPSlots("mobiles_clp", "Mobiles & Tablets", 700000, 95),
  ...generateCLPSlots("laptops_clp", "Laptops & Computers", 500000, 85),
  ...generateCLPSlots("tv_clp", "TV & Home Entertainment", 450000, 80),
  ...generateCLPSlots("gaming_clp", "Gaming & Consoles", 600000, 90),
  ...generateCLPSlots("cameras_clp", "Cameras & Photography", 300000, 70),
  ...generateCLPSlots("wearables_clp", "Wearables & Smartwatches", 400000, 75),
  // Fashion CLPs
  ...generateCLPSlots("fashion_clp", "Fashion", 750000, 90),
  ...generateCLPSlots("men_fashion_clp", "Men's Fashion", 500000, 80),
  ...generateCLPSlots("women_fashion_clp", "Women's Fashion", 600000, 85),
  ...generateCLPSlots("kids_fashion_clp", "Kids Fashion", 400000, 70),
  ...generateCLPSlots("shoes_clp", "Shoes & Footwear", 450000, 75),
  ...generateCLPSlots("watches_clp", "Watches", 350000, 70),
  ...generateCLPSlots("jewelry_clp", "Jewelry", 300000, 65),
  ...generateCLPSlots("eyewear_clp", "Eyewear", 250000, 60),
  // Beauty & Personal Care CLPs
  ...generateCLPSlots("beauty_clp", "Beauty", 550000, 80),
  ...generateCLPSlots("skincare_clp", "Skincare", 450000, 75),
  ...generateCLPSlots("makeup_clp", "Makeup", 400000, 70),
  ...generateCLPSlots("fragrance_clp", "Fragrances", 350000, 70),
  ...generateCLPSlots("haircare_clp", "Haircare", 300000, 65),
  ...generateCLPSlots("grooming_clp", "Men's Grooming", 250000, 60),
  // Home & Living CLPs
  ...generateCLPSlots("home_clp", "Home & Kitchen", 500000, 80),
  ...generateCLPSlots("furniture_clp", "Furniture", 350000, 70),
  ...generateCLPSlots("kitchen_clp", "Kitchen Appliances", 400000, 75),
  ...generateCLPSlots("home_decor_clp", "Home Decor", 300000, 65),
  ...generateCLPSlots("bedding_clp", "Bedding & Bath", 280000, 60),
  ...generateCLPSlots("garden_clp", "Garden & Outdoor", 200000, 55),
  // Baby & Kids CLPs
  ...generateCLPSlots("babies_clp", "Babies & Toys", 600000, 85),
  ...generateCLPSlots("toys_clp", "Toys & Games", 500000, 80),
  ...generateCLPSlots("baby_gear_clp", "Baby Gear", 350000, 70),
  ...generateCLPSlots("baby_care_clp", "Baby Care", 400000, 75),
  // Sports & Outdoors CLPs
  ...generateCLPSlots("sports_clp", "Sports & Outdoors", 450000, 75),
  ...generateCLPSlots("fitness_clp", "Fitness & Exercise", 350000, 70),
  ...generateCLPSlots("outdoor_clp", "Outdoor Recreation", 250000, 60),
  ...generateCLPSlots("cycling_clp", "Cycling", 200000, 55),
  // Grocery & Essentials CLPs
  ...generateCLPSlots("grocery_clp", "Grocery", 700000, 90),
  ...generateCLPSlots("beverages_clp", "Beverages", 400000, 70),
  ...generateCLPSlots("snacks_clp", "Snacks & Confectionery", 350000, 65),
  ...generateCLPSlots("household_clp", "Household Essentials", 450000, 75),
  ...generateCLPSlots("pet_supplies_clp", "Pet Supplies", 250000, 60),
  // Other CLPs
  ...generateCLPSlots("automotive_clp", "Automotive", 300000, 65),
  ...generateCLPSlots("books_clp", "Books & Media", 200000, 55),
  ...generateCLPSlots("office_clp", "Office Supplies", 250000, 60),
  ...generateCLPSlots("health_clp", "Health & Wellness", 400000, 75),
];

// Booked time slots for CPT availability (mock)
// Format: { slotId: { "YYYY-MM-DD": ["HH:MM-HH:MM", ...] } }
// Hours are 0-23 (midnight to midnight). A full day is all 24 hours booked.
export const bookedTimeSlots: Record<string, Record<string, string[]>> = {
  hp_hero: {
    // February 2026
    "2026-02-05": ["00:00-23:59"], // Full day - Today (for demo)
    "2026-02-06": ["08:00-18:00"], // Business hours
    "2026-02-07": ["00:00-23:59"], // Full day - Weekend
    "2026-02-08": ["00:00-23:59"], // Full day - Weekend
    "2026-02-12": ["00:00-23:59"], // Full day - Fully booked
    "2026-02-14": ["00:00-23:59"], // Full day - Valentine's Day
    "2026-02-15": ["00:00-23:59"], // Full day
    "2026-02-18": ["06:00-14:00"], // Morning shift
    "2026-02-19": ["00:00-23:59"], // Full day
    "2026-02-20": ["12:00-20:00"], // Afternoon/evening
    "2026-02-21": ["00:00-23:59"], // Full day - Weekend
    "2026-02-22": ["00:00-23:59"], // Full day - Weekend
    "2026-02-25": ["09:00-17:00"], // Business hours
    // March 2026
    "2026-03-01": ["00:00-23:59"], // Full day
    "2026-03-07": ["00:00-23:59"], // Full day - Weekend
    "2026-03-08": ["00:00-23:59"], // Full day - Women's Day
    "2026-03-14": ["00:00-23:59"], // Full day - Weekend
    "2026-03-15": ["00:00-23:59"], // Full day - Weekend
    "2026-03-20": ["10:00-22:00"], // Extended hours
    "2026-03-21": ["00:00-23:59"], // Full day - Weekend
  },
  hp_top_fold: {
    "2026-02-06": ["16:00-23:59"], // Evening
    "2026-02-07": ["00:00-23:59"], // Full day
    "2026-02-12": ["00:00-23:59"], // Full day - Fully booked
    "2026-02-14": ["00:00-23:59"], // Full day
    "2026-02-15": ["14:00-22:00"], // Afternoon/evening
    "2026-02-21": ["00:00-23:59"], // Full day
    "2026-02-28": ["00:00-23:59"], // Full day
    "2026-03-07": ["00:00-23:59"], // Full day
    "2026-03-14": ["00:00-23:59"], // Full day
  },
  hp_second_fold: {
    "2026-02-07": ["00:00-23:59"], // Full day
    "2026-02-08": ["00:00-23:59"], // Full day
    "2026-02-12": ["00:00-23:59"], // Full day - Fully booked
    "2026-02-14": ["00:00-23:59"], // Full day
    "2026-02-21": ["00:00-23:59"], // Full day
    "2026-02-22": ["12:00-20:00"], // Afternoon
    "2026-03-01": ["00:00-23:59"], // Full day
  },
  search_hero: {
    "2026-02-06": ["00:00-23:59"], // Full day
    "2026-02-07": ["06:00-18:00"], // Extended morning
    "2026-02-12": ["00:00-23:59"], // Full day - Fully booked
    "2026-02-14": ["00:00-23:59"], // Full day
    "2026-02-15": ["00:00-23:59"], // Full day
    "2026-02-20": ["00:00-12:00"], // Morning
    "2026-02-28": ["00:00-23:59"], // Full day
  },
  search_top_fold: {
    "2026-02-05": ["00:00-23:59"], // Full day
    "2026-02-06": ["08:00-16:00"], // Business hours
    "2026-02-12": ["00:00-23:59"], // Full day - Fully booked
    "2026-02-14": ["00:00-23:59"], // Full day
    "2026-02-15": ["00:00-23:59"], // Full day
    "2026-02-21": ["10:00-18:00"], // Mid-day
    "2026-02-22": ["00:00-23:59"], // Full day
    "2026-03-01": ["00:00-23:59"], // Full day
    "2026-03-08": ["00:00-23:59"], // Full day
  },
  electronics_clp_hero: {
    "2026-02-05": ["00:00-08:00"], // Early morning
    "2026-02-10": ["00:00-23:59"], // Full day
    "2026-02-11": ["00:00-23:59"], // Full day
    "2026-02-12": ["00:00-23:59"], // Full day
    "2026-02-13": ["00:00-23:59"], // Full day
    "2026-02-14": ["00:00-23:59"], // Full day - Valentine's
    "2026-02-20": ["14:00-22:00"], // Evening
    "2026-02-21": ["00:00-23:59"], // Full day
    "2026-03-05": ["00:00-23:59"], // Full day
    "2026-03-06": ["09:00-21:00"], // Extended day
  },
  fashion_clp_hero: {
    "2026-02-05": ["10:00-18:00"], // Partial day
    "2026-02-06": ["00:00-23:59"], // Full day
    "2026-02-07": ["00:00-12:00"], // Morning
    "2026-02-12": ["00:00-23:59"], // Full day - Fully booked
    "2026-02-14": ["00:00-23:59"], // Full day - Valentine's
    "2026-02-15": ["06:00-15:00"], // Morning to afternoon
    "2026-02-16": ["12:00-20:00"], // Afternoon to evening
    "2026-02-21": ["00:00-23:59"], // Full day
    "2026-02-22": ["00:00-23:59"], // Full day
    "2026-02-28": ["00:00-23:59"], // Full day
    "2026-03-01": ["00:00-23:59"], // Full day
    "2026-03-08": ["00:00-23:59"], // Full day
  },
  beauty_clp_hero: {
    "2026-02-12": ["00:00-23:59"], // Full day - Fully booked
    "2026-02-14": ["00:00-23:59"], // Full day
    "2026-02-21": ["00:00-23:59"], // Full day
    "2026-03-08": ["00:00-23:59"], // Full day - Women's Day
  },
};

// Legacy format for backward compatibility
export const bookedDates: Record<string, string[]> = {
  hp_hero: ["2026-02-05", "2026-02-06", "2026-02-07", "2026-02-08", "2026-02-14", "2026-02-15", "2026-02-18", "2026-02-19", "2026-02-20", "2026-02-21", "2026-02-22", "2026-02-25", "2026-03-01", "2026-03-07", "2026-03-08", "2026-03-14", "2026-03-15", "2026-03-20", "2026-03-21"],
  hp_top_fold: ["2026-02-06", "2026-02-07", "2026-02-14", "2026-02-15", "2026-02-21", "2026-02-28", "2026-03-07", "2026-03-14"],
  hp_second_fold: ["2026-02-07", "2026-02-08", "2026-02-12", "2026-02-14", "2026-02-21", "2026-02-22", "2026-03-01"],
  search_hero: ["2026-02-06", "2026-02-07", "2026-02-12", "2026-02-14", "2026-02-15", "2026-02-20", "2026-02-28"],
  electronics_clp_hero: ["2026-02-05", "2026-02-10", "2026-02-11", "2026-02-12", "2026-02-13", "2026-02-14", "2026-02-20", "2026-02-21", "2026-03-05", "2026-03-06"],
};

export const brands = [
  { id: "samsung", name: "Samsung" },
  { id: "apple", name: "Apple" },
  { id: "sony", name: "Sony" },
  { id: "lg", name: "LG" },
  { id: "nike", name: "Nike" },
  { id: "adidas", name: "Adidas" },
  { id: "loreal", name: "L'Oréal" },
  { id: "nivea", name: "Nivea" },
  { id: "nestle", name: "Nestlé" },
  { id: "pampers", name: "Pampers" },
  { id: "al_majed_oud", name: "Al Majed Oud" },
  { id: "12dry", name: "12dry" },
];

export const categories = [
  { 
    id: "electronics", 
    name: "Electronics & Mobiles",
    subcategories: [
      { id: "electronics_mobile", name: "Mobile Phones" },
      { id: "electronics_tablets", name: "Tablets" },
      { id: "electronics_laptops", name: "Laptops" },
      { id: "electronics_tv", name: "TVs & Monitors" },
      { id: "electronics_cameras", name: "Cameras" },
      { id: "electronics_audio", name: "Audio & Headphones" },
      { id: "electronics_gaming", name: "Gaming" },
    ]
  },
  { 
    id: "fashion", 
    name: "Fashion",
    subcategories: [
      { id: "fashion_mens", name: "Men's Clothing" },
      { id: "fashion_womens", name: "Women's Clothing" },
      { id: "fashion_kids", name: "Kids' Clothing" },
      { id: "fashion_shoes", name: "Shoes" },
      { id: "fashion_watches", name: "Watches" },
      { id: "fashion_jewelry", name: "Jewelry" },
    ]
  },
  { 
    id: "beauty", 
    name: "Beauty & Personal Care",
    subcategories: [
      { id: "beauty_skincare", name: "Skincare" },
      { id: "beauty_makeup", name: "Makeup" },
      { id: "beauty_fragrance", name: "Fragrance" },
      { id: "beauty_haircare", name: "Haircare" },
    ]
  },
  { 
    id: "home", 
    name: "Home & Kitchen",
    subcategories: [
      { id: "home_furniture", name: "Furniture" },
      { id: "home_appliances", name: "Home Appliances" },
      { id: "home_decor", name: "Home Decor" },
      { id: "home_kitchen", name: "Kitchen & Dining" },
    ]
  },
  { 
    id: "grocery", 
    name: "Grocery & Essentials",
    subcategories: [
      { id: "grocery_food", name: "Food & Beverages" },
      { id: "grocery_household", name: "Household" },
      { id: "grocery_pet", name: "Pet Supplies" },
    ]
  },
  { id: "baby", name: "Baby & Kids", subcategories: [] },
  { id: "sports", name: "Sports & Outdoors", subcategories: [] },
  { id: "health", name: "Health & Nutrition", subcategories: [] },
  { id: "automotive", name: "Automotive", subcategories: [] },
  { id: "toys", name: "Toys & Games", subcategories: [] },
];

export const fulfillmentOptions = [
  { id: "express", name: "noon Express", description: "Fulfilled by noon" },
  { id: "supermall", name: "Supermall", description: "Marketplace sellers" },
];

export const sellers = [
  { id: "noon", name: "noon" },
  { id: "greentree", name: "GreenTree" },
  { id: "maishop", name: "MAISHOP" },
  { id: "trizone", name: "Trizone" },
  { id: "dmkcoopic", name: "DMKCOOPIC_UAE" },
  { id: "geekay", name: "GEEKAY" },
  { id: "jajeek", name: "JAJEEK" },
  { id: "elite", name: "Elite general trading FZC LLC" },
  { id: "jumbo", name: "Jumbo Electronics" },
  { id: "sharaf", name: "Sharaf DG" },
];

export const products = [
  // ==================== ELECTRONICS ====================
  // Mobile Phones
  {
    id: "prod_1",
    name: "Apple iPhone 15 Pro Max 256GB Natural Titanium",
    image: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=200&h=200&fit=crop",
    price: 4999,
    originalPrice: 5499,
    currency: "AED",
    fulfillment: "express",
    seller: "noon",
    category: "electronics",
    subcategory: "electronics_mobile",
    brand: "apple",
  },
  {
    id: "prod_2",
    name: "Samsung Galaxy S24 Ultra 512GB Titanium Black",
    image: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=200&h=200&fit=crop",
    price: 4799,
    originalPrice: 5299,
    currency: "AED",
    fulfillment: "express",
    seller: "noon",
    category: "electronics",
    subcategory: "electronics_mobile",
    brand: "samsung",
  },
  {
    id: "prod_3",
    name: "Samsung Galaxy Z Fold5 512GB Phantom Black",
    image: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=200&h=200&fit=crop",
    price: 6499,
    originalPrice: 7499,
    currency: "AED",
    fulfillment: "express",
    seller: "jumbo",
    category: "electronics",
    subcategory: "electronics_mobile",
    brand: "samsung",
  },
  {
    id: "prod_4",
    name: "Sony Xperia 1 V 256GB Black - 5G",
    image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=200&h=200&fit=crop",
    price: 4299,
    originalPrice: null,
    currency: "AED",
    fulfillment: "supermall",
    seller: "sharaf",
    category: "electronics",
    subcategory: "electronics_mobile",
    brand: "sony",
  },
  // Tablets
  {
    id: "prod_5",
    name: "Apple iPad Pro 12.9-inch M2 Chip 256GB WiFi Space Gray",
    image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=200&h=200&fit=crop",
    price: 4999,
    originalPrice: 5499,
    currency: "AED",
    fulfillment: "express",
    seller: "noon",
    category: "electronics",
    subcategory: "electronics_tablets",
    brand: "apple",
  },
  {
    id: "prod_6",
    name: "Samsung Galaxy Tab S9 Ultra 512GB WiFi Graphite",
    image: "https://images.unsplash.com/photo-1561154464-82e9adf32764?w=200&h=200&fit=crop",
    price: 4599,
    originalPrice: 5199,
    currency: "AED",
    fulfillment: "express",
    seller: "noon",
    category: "electronics",
    subcategory: "electronics_tablets",
    brand: "samsung",
  },
  // Laptops
  {
    id: "prod_7",
    name: "Apple MacBook Pro 14-inch M3 Pro 18GB RAM 512GB SSD",
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=200&h=200&fit=crop",
    price: 8999,
    originalPrice: 9499,
    currency: "AED",
    fulfillment: "express",
    seller: "noon",
    category: "electronics",
    subcategory: "electronics_laptops",
    brand: "apple",
  },
  {
    id: "prod_8",
    name: "Samsung Galaxy Book3 Ultra 16-inch i9 32GB 1TB RTX 4070",
    image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=200&h=200&fit=crop",
    price: 11999,
    originalPrice: 13499,
    currency: "AED",
    fulfillment: "express",
    seller: "jumbo",
    category: "electronics",
    subcategory: "electronics_laptops",
    brand: "samsung",
  },
  {
    id: "prod_9",
    name: "LG Gram 17 Ultra-Lightweight Laptop i7 16GB 1TB",
    image: "https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=200&h=200&fit=crop",
    price: 6499,
    originalPrice: 7299,
    currency: "AED",
    fulfillment: "supermall",
    seller: "geekay",
    category: "electronics",
    subcategory: "electronics_laptops",
    brand: "lg",
  },
  // TVs & Monitors
  {
    id: "prod_10",
    name: "Samsung 85 Inch Neo QLED 8K Smart TV QN900D",
    image: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=200&h=200&fit=crop",
    price: 30998,
    originalPrice: 36999,
    currency: "AED",
    fulfillment: "express",
    seller: "noon",
    category: "electronics",
    subcategory: "electronics_tv",
    brand: "samsung",
  },
  {
    id: "prod_11",
    name: "LG 77 Inch OLED evo G4 4K Smart TV with AI",
    image: "https://images.unsplash.com/photo-1461151304267-38535e780c79?w=200&h=200&fit=crop",
    price: 14999,
    originalPrice: 17999,
    currency: "AED",
    fulfillment: "express",
    seller: "jumbo",
    category: "electronics",
    subcategory: "electronics_tv",
    brand: "lg",
  },
  {
    id: "prod_12",
    name: "Sony Bravia XR 65 Inch 4K OLED Google TV A95L",
    image: "https://images.unsplash.com/photo-1567690187548-f07b1d7bf5a9?w=200&h=200&fit=crop",
    price: 12999,
    originalPrice: 14999,
    currency: "AED",
    fulfillment: "express",
    seller: "sharaf",
    category: "electronics",
    subcategory: "electronics_tv",
    brand: "sony",
  },
  // Audio & Headphones
  {
    id: "prod_13",
    name: "Apple AirPods Pro 2nd Generation with MagSafe Case",
    image: "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=200&h=200&fit=crop",
    price: 899,
    originalPrice: 999,
    currency: "AED",
    fulfillment: "express",
    seller: "noon",
    category: "electronics",
    subcategory: "electronics_audio",
    brand: "apple",
  },
  {
    id: "prod_14",
    name: "Sony WH-1000XM5 Wireless Noise Cancelling Headphones Black",
    image: "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=200&h=200&fit=crop",
    price: 1299,
    originalPrice: 1499,
    currency: "AED",
    fulfillment: "express",
    seller: "sharaf",
    category: "electronics",
    subcategory: "electronics_audio",
    brand: "sony",
  },
  {
    id: "prod_15",
    name: "Samsung Galaxy Buds2 Pro True Wireless Earbuds Graphite",
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=200&h=200&fit=crop",
    price: 549,
    originalPrice: 699,
    currency: "AED",
    fulfillment: "express",
    seller: "noon",
    category: "electronics",
    subcategory: "electronics_audio",
    brand: "samsung",
  },
  {
    id: "prod_16",
    name: "LG XBOOM Go XG9 Portable Bluetooth Speaker",
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=200&h=200&fit=crop",
    price: 899,
    originalPrice: 1099,
    currency: "AED",
    fulfillment: "supermall",
    seller: "geekay",
    category: "electronics",
    subcategory: "electronics_audio",
    brand: "lg",
  },
  // Cameras
  {
    id: "prod_17",
    name: "Sony Alpha A7 IV Mirrorless Camera Body Only",
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=200&h=200&fit=crop",
    price: 9499,
    originalPrice: 10499,
    currency: "AED",
    fulfillment: "express",
    seller: "sharaf",
    category: "electronics",
    subcategory: "electronics_cameras",
    brand: "sony",
  },
  {
    id: "prod_18",
    name: "Samsung Galaxy Camera 360 Pro 8K Recording",
    image: "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=200&h=200&fit=crop",
    price: 1299,
    originalPrice: 1499,
    currency: "AED",
    fulfillment: "supermall",
    seller: "dmkcoopic",
    category: "electronics",
    subcategory: "electronics_cameras",
    brand: "samsung",
  },
  // Gaming
  {
    id: "prod_19",
    name: "Sony PlayStation 5 Slim Digital Edition Console",
    image: "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=200&h=200&fit=crop",
    price: 1799,
    originalPrice: 1999,
    currency: "AED",
    fulfillment: "express",
    seller: "noon",
    category: "electronics",
    subcategory: "electronics_gaming",
    brand: "sony",
  },
  {
    id: "prod_20",
    name: "Sony DualSense Edge Wireless Controller PS5",
    image: "https://images.unsplash.com/photo-1592840496694-26d035b52b48?w=200&h=200&fit=crop",
    price: 799,
    originalPrice: 899,
    currency: "AED",
    fulfillment: "express",
    seller: "geekay",
    category: "electronics",
    subcategory: "electronics_gaming",
    brand: "sony",
  },

  // ==================== FASHION ====================
  // Men's Clothing
  {
    id: "prod_21",
    name: "Nike Sportswear Tech Fleece Hoodie Men's - Black",
    image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=200&h=200&fit=crop",
    price: 449,
    originalPrice: 549,
    currency: "AED",
    fulfillment: "express",
    seller: "noon",
    category: "fashion",
    subcategory: "fashion_mens",
    brand: "nike",
  },
  {
    id: "prod_22",
    name: "Adidas Essentials 3-Stripes Tracksuit Men's Navy",
    image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=200&h=200&fit=crop",
    price: 349,
    originalPrice: 429,
    currency: "AED",
    fulfillment: "express",
    seller: "noon",
    category: "fashion",
    subcategory: "fashion_mens",
    brand: "adidas",
  },
  // Women's Clothing
  {
    id: "prod_23",
    name: "Nike Sportswear Essential Women's Fleece Crew Pink",
    image: "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=200&h=200&fit=crop",
    price: 299,
    originalPrice: 379,
    currency: "AED",
    fulfillment: "express",
    seller: "noon",
    category: "fashion",
    subcategory: "fashion_womens",
    brand: "nike",
  },
  {
    id: "prod_24",
    name: "Adidas Originals Trefoil Dress Women's Black",
    image: "https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=200&h=200&fit=crop",
    price: 249,
    originalPrice: 299,
    currency: "AED",
    fulfillment: "supermall",
    seller: "maishop",
    category: "fashion",
    subcategory: "fashion_womens",
    brand: "adidas",
  },
  // Kids' Clothing
  {
    id: "prod_25",
    name: "Nike Kids Air Jordan 1 Mid SE Boys Sneakers",
    image: "https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?w=200&h=200&fit=crop",
    price: 399,
    originalPrice: 479,
    currency: "AED",
    fulfillment: "express",
    seller: "noon",
    category: "fashion",
    subcategory: "fashion_kids",
    brand: "nike",
  },
  {
    id: "prod_26",
    name: "Adidas Kids Superstar CF Shoes White/Black",
    image: "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=200&h=200&fit=crop",
    price: 279,
    originalPrice: 329,
    currency: "AED",
    fulfillment: "express",
    seller: "noon",
    category: "fashion",
    subcategory: "fashion_kids",
    brand: "adidas",
  },
  // Shoes
  {
    id: "prod_27",
    name: "Nike Air Max 270 Men's Running Shoes Black/White",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=200&h=200&fit=crop",
    price: 549,
    originalPrice: 699,
    currency: "AED",
    fulfillment: "express",
    seller: "noon",
    category: "fashion",
    subcategory: "fashion_shoes",
    brand: "nike",
  },
  {
    id: "prod_28",
    name: "Adidas Ultraboost Light Running Shoes Core Black",
    image: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=200&h=200&fit=crop",
    price: 649,
    originalPrice: 799,
    currency: "AED",
    fulfillment: "express",
    seller: "noon",
    category: "fashion",
    subcategory: "fashion_shoes",
    brand: "adidas",
  },
  {
    id: "prod_29",
    name: "Nike Air Force 1 '07 Women's Shoes White",
    image: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=200&h=200&fit=crop",
    price: 449,
    originalPrice: 529,
    currency: "AED",
    fulfillment: "supermall",
    seller: "trizone",
    category: "fashion",
    subcategory: "fashion_shoes",
    brand: "nike",
  },
  // Watches
  {
    id: "prod_30",
    name: "Apple Watch Series 9 GPS 45mm Midnight Aluminum",
    image: "https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=200&h=200&fit=crop",
    price: 1699,
    originalPrice: 1899,
    currency: "AED",
    fulfillment: "express",
    seller: "noon",
    category: "fashion",
    subcategory: "fashion_watches",
    brand: "apple",
  },
  {
    id: "prod_31",
    name: "Samsung Galaxy Watch6 Classic 47mm Silver LTE",
    image: "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=200&h=200&fit=crop",
    price: 1499,
    originalPrice: 1699,
    currency: "AED",
    fulfillment: "express",
    seller: "noon",
    category: "fashion",
    subcategory: "fashion_watches",
    brand: "samsung",
  },

  // ==================== BEAUTY & PERSONAL CARE ====================
  // Skincare
  {
    id: "prod_32",
    name: "L'Oréal Paris Revitalift Laser X3 Anti-Aging Day Cream 50ml",
    image: "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=200&h=200&fit=crop",
    price: 129,
    originalPrice: 159,
    currency: "AED",
    fulfillment: "express",
    seller: "noon",
    category: "beauty",
    subcategory: "beauty_skincare",
    brand: "loreal",
  },
  {
    id: "prod_33",
    name: "Nivea Soft Refreshingly Soft Moisturizing Cream 200ml",
    image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=200&h=200&fit=crop",
    price: 25,
    originalPrice: 35,
    currency: "AED",
    fulfillment: "express",
    seller: "noon",
    category: "beauty",
    subcategory: "beauty_skincare",
    brand: "nivea",
  },
  {
    id: "prod_34",
    name: "L'Oréal Paris Hyaluron Expert Replumping Serum 30ml",
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=200&h=200&fit=crop",
    price: 99,
    originalPrice: 129,
    currency: "AED",
    fulfillment: "express",
    seller: "noon",
    category: "beauty",
    subcategory: "beauty_skincare",
    brand: "loreal",
  },
  {
    id: "prod_35",
    name: "Nivea Men Deep Clean Face Wash 100ml",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=200&h=200&fit=crop",
    price: 29,
    originalPrice: 39,
    currency: "AED",
    fulfillment: "supermall",
    seller: "greentree",
    category: "beauty",
    subcategory: "beauty_skincare",
    brand: "nivea",
  },
  // Makeup
  {
    id: "prod_36",
    name: "L'Oréal Paris Infallible 24H Fresh Wear Foundation",
    image: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=200&h=200&fit=crop",
    price: 89,
    originalPrice: 109,
    currency: "AED",
    fulfillment: "express",
    seller: "noon",
    category: "beauty",
    subcategory: "beauty_makeup",
    brand: "loreal",
  },
  {
    id: "prod_37",
    name: "L'Oréal Paris Volume Million Lashes Mascara Black",
    image: "https://images.unsplash.com/photo-1631214524020-7e18db9a8f92?w=200&h=200&fit=crop",
    price: 69,
    originalPrice: 89,
    currency: "AED",
    fulfillment: "express",
    seller: "noon",
    category: "beauty",
    subcategory: "beauty_makeup",
    brand: "loreal",
  },
  // Fragrance
  {
    id: "prod_38",
    name: "Al Majed Oud Royal Amber Perfume 100ml EDP",
    image: "https://images.unsplash.com/photo-1541643600914-78b084683601?w=200&h=200&fit=crop",
    price: 399,
    originalPrice: 499,
    currency: "AED",
    fulfillment: "express",
    seller: "noon",
    category: "beauty",
    subcategory: "beauty_fragrance",
    brand: "al_majed_oud",
  },
  {
    id: "prod_39",
    name: "Al Majed Oud Musk Tahara Premium Collection 12ml",
    image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?w=200&h=200&fit=crop",
    price: 149,
    originalPrice: 189,
    currency: "AED",
    fulfillment: "supermall",
    seller: "jajeek",
    category: "beauty",
    subcategory: "beauty_fragrance",
    brand: "al_majed_oud",
  },
  // Haircare
  {
    id: "prod_40",
    name: "L'Oréal Paris Elvive Total Repair 5 Shampoo 400ml",
    image: "https://images.unsplash.com/photo-1526947425960-945c6e72858f?w=200&h=200&fit=crop",
    price: 35,
    originalPrice: 45,
    currency: "AED",
    fulfillment: "express",
    seller: "noon",
    category: "beauty",
    subcategory: "beauty_haircare",
    brand: "loreal",
  },
  {
    id: "prod_41",
    name: "Nivea Hair Care Micellar Shampoo Deep Clean 400ml",
    image: "https://images.unsplash.com/photo-1585232351009-aa27d5a25986?w=200&h=200&fit=crop",
    price: 32,
    originalPrice: 42,
    currency: "AED",
    fulfillment: "supermall",
    seller: "greentree",
    category: "beauty",
    subcategory: "beauty_haircare",
    brand: "nivea",
  },

  // ==================== HOME & KITCHEN ====================
  // Furniture
  {
    id: "prod_42",
    name: "IKEA MALM Queen Bed Frame with Storage Oak Veneer",
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=200&h=200&fit=crop",
    price: 1299,
    originalPrice: 1499,
    currency: "AED",
    fulfillment: "supermall",
    seller: "elite",
    category: "home",
    subcategory: "home_furniture",
    brand: null,
  },
  {
    id: "prod_43",
    name: "Modern L-Shaped Sectional Sofa Grey Fabric",
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=200&h=200&fit=crop",
    price: 2499,
    originalPrice: 2999,
    currency: "AED",
    fulfillment: "supermall",
    seller: "maishop",
    category: "home",
    subcategory: "home_furniture",
    brand: null,
  },
  // Home Appliances
  {
    id: "prod_44",
    name: "Samsung Bespoke French Door Refrigerator 820L",
    image: "https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=200&h=200&fit=crop",
    price: 8999,
    originalPrice: 10499,
    currency: "AED",
    fulfillment: "express",
    seller: "noon",
    category: "home",
    subcategory: "home_appliances",
    brand: "samsung",
  },
  {
    id: "prod_45",
    name: "LG ThinQ Front Load Washer Dryer Combo 10.5/7kg",
    image: "https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=200&h=200&fit=crop",
    price: 4499,
    originalPrice: 5299,
    currency: "AED",
    fulfillment: "express",
    seller: "jumbo",
    category: "home",
    subcategory: "home_appliances",
    brand: "lg",
  },
  {
    id: "prod_46",
    name: "Samsung WindFree Split AC 2 Ton Inverter",
    image: "https://images.unsplash.com/photo-1585338107529-13afc5f02586?w=200&h=200&fit=crop",
    price: 3299,
    originalPrice: 3999,
    currency: "AED",
    fulfillment: "express",
    seller: "sharaf",
    category: "home",
    subcategory: "home_appliances",
    brand: "samsung",
  },
  // Kitchen & Dining
  {
    id: "prod_47",
    name: "Nestlé Nespresso Vertuo Next Coffee Machine Black",
    image: "https://images.unsplash.com/photo-1517487881594-2787fef5ebf7?w=200&h=200&fit=crop",
    price: 599,
    originalPrice: 799,
    currency: "AED",
    fulfillment: "express",
    seller: "noon",
    category: "home",
    subcategory: "home_kitchen",
    brand: "nestle",
  },
  {
    id: "prod_48",
    name: "Samsung Smart Microwave Oven with Grill 40L",
    image: "https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?w=200&h=200&fit=crop",
    price: 699,
    originalPrice: 849,
    currency: "AED",
    fulfillment: "express",
    seller: "noon",
    category: "home",
    subcategory: "home_kitchen",
    brand: "samsung",
  },

  // ==================== GROCERY & ESSENTIALS ====================
  // Food & Beverages
  {
    id: "prod_49",
    name: "Nestlé Nescafé Gold Instant Coffee 200g",
    image: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=200&h=200&fit=crop",
    price: 49,
    originalPrice: 59,
    currency: "AED",
    fulfillment: "express",
    seller: "noon",
    category: "grocery",
    subcategory: "grocery_food",
    brand: "nestle",
  },
  {
    id: "prod_50",
    name: "Nestlé KitKat Chunky Chocolate Bar Pack of 24",
    image: "https://images.unsplash.com/photo-1575377427642-087cf684f29d?w=200&h=200&fit=crop",
    price: 89,
    originalPrice: 109,
    currency: "AED",
    fulfillment: "express",
    seller: "noon",
    category: "grocery",
    subcategory: "grocery_food",
    brand: "nestle",
  },
  {
    id: "prod_51",
    name: "Nestlé Cerelac Wheat with Milk Baby Cereal 1kg",
    image: "https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?w=200&h=200&fit=crop",
    price: 59,
    originalPrice: 69,
    currency: "AED",
    fulfillment: "supermall",
    seller: "greentree",
    category: "grocery",
    subcategory: "grocery_food",
    brand: "nestle",
  },
  // Household
  {
    id: "prod_52",
    name: "12dry Ultra Absorbent Kitchen Towels 8 Rolls",
    image: "https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=200&h=200&fit=crop",
    price: 35,
    originalPrice: 45,
    currency: "AED",
    fulfillment: "express",
    seller: "noon",
    category: "grocery",
    subcategory: "grocery_household",
    brand: "12dry",
  },
  {
    id: "prod_53",
    name: "12dry Premium Toilet Paper 24 Mega Rolls",
    image: "https://images.unsplash.com/photo-1584556812952-905ffd0c611a?w=200&h=200&fit=crop",
    price: 49,
    originalPrice: 59,
    currency: "AED",
    fulfillment: "express",
    seller: "noon",
    category: "grocery",
    subcategory: "grocery_household",
    brand: "12dry",
  },

  // ==================== BABY & KIDS ====================
  {
    id: "prod_54",
    name: "Pampers Premium Care Diapers Size 4 (9-14kg) 88 Count",
    image: "https://images.unsplash.com/photo-1584839404042-8bc36c3e025b?w=200&h=200&fit=crop",
    price: 89,
    originalPrice: 109,
    currency: "AED",
    fulfillment: "express",
    seller: "noon",
    category: "baby",
    subcategory: null,
    brand: "pampers",
  },
  {
    id: "prod_55",
    name: "Pampers Baby-Dry Night Diapers Size 5 (11-16kg) 58 Count",
    image: "https://images.unsplash.com/photo-1590080876351-941da357a5ce?w=200&h=200&fit=crop",
    price: 79,
    originalPrice: 99,
    currency: "AED",
    fulfillment: "express",
    seller: "noon",
    category: "baby",
    subcategory: null,
    brand: "pampers",
  },
  {
    id: "prod_56",
    name: "Pampers Aqua Pure Baby Wipes 9 Packs (432 Wipes)",
    image: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=200&h=200&fit=crop",
    price: 69,
    originalPrice: 85,
    currency: "AED",
    fulfillment: "supermall",
    seller: "greentree",
    category: "baby",
    subcategory: null,
    brand: "pampers",
  },
  {
    id: "prod_57",
    name: "Nestlé NAN Optipro Stage 3 Growing Up Milk 800g",
    image: "https://images.unsplash.com/photo-1558939263-a088c8dc2e4c?w=200&h=200&fit=crop",
    price: 79,
    originalPrice: 95,
    currency: "AED",
    fulfillment: "express",
    seller: "noon",
    category: "baby",
    subcategory: null,
    brand: "nestle",
  },

  // ==================== SPORTS & OUTDOORS ====================
  {
    id: "prod_58",
    name: "Nike Pro Dri-FIT Training Tank Men's Black",
    image: "https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=200&h=200&fit=crop",
    price: 149,
    originalPrice: 179,
    currency: "AED",
    fulfillment: "express",
    seller: "noon",
    category: "sports",
    subcategory: null,
    brand: "nike",
  },
  {
    id: "prod_59",
    name: "Adidas Predator Accuracy.1 FG Football Boots",
    image: "https://images.unsplash.com/photo-1511886929837-354d827aae26?w=200&h=200&fit=crop",
    price: 899,
    originalPrice: 1099,
    currency: "AED",
    fulfillment: "express",
    seller: "noon",
    category: "sports",
    subcategory: null,
    brand: "adidas",
  },
  {
    id: "prod_60",
    name: "Nike Brasilia 9.5 Training Duffel Bag Large",
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=200&h=200&fit=crop",
    price: 179,
    originalPrice: 219,
    currency: "AED",
    fulfillment: "supermall",
    seller: "trizone",
    category: "sports",
    subcategory: null,
    brand: "nike",
  },

  // ==================== HEALTH & NUTRITION ====================
  {
    id: "prod_61",
    name: "Nestlé Optifast VLCD Chocolate Shake 12 Sachets",
    image: "https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?w=200&h=200&fit=crop",
    price: 199,
    originalPrice: 249,
    currency: "AED",
    fulfillment: "express",
    seller: "noon",
    category: "health",
    subcategory: null,
    brand: "nestle",
  },
  {
    id: "prod_62",
    name: "Nivea Sun Protect & Moisture SPF50+ Lotion 200ml",
    image: "https://images.unsplash.com/photo-1556227703-2cca59d5e0a1?w=200&h=200&fit=crop",
    price: 59,
    originalPrice: 75,
    currency: "AED",
    fulfillment: "express",
    seller: "noon",
    category: "health",
    subcategory: null,
    brand: "nivea",
  },

  // ==================== TOYS & GAMES ====================
  {
    id: "prod_63",
    name: "Sony PlayStation 5 DualSense Controller Cosmic Red",
    image: "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=200&h=200&fit=crop",
    price: 299,
    originalPrice: 349,
    currency: "AED",
    fulfillment: "express",
    seller: "geekay",
    category: "toys",
    subcategory: null,
    brand: "sony",
  },
  {
    id: "prod_64",
    name: "LEGO Star Wars Millennium Falcon Ultimate Collector 7541 Pieces",
    image: "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=200&h=200&fit=crop",
    price: 3299,
    originalPrice: 3699,
    currency: "AED",
    fulfillment: "supermall",
    seller: "jajeek",
    category: "toys",
    subcategory: null,
    brand: null,
  },

  // ==================== AUTOMOTIVE ====================
  {
    id: "prod_65",
    name: "Samsung 70mai Dash Cam A800S 4K GPS ADAS",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=200&h=200&fit=crop",
    price: 599,
    originalPrice: 749,
    currency: "AED",
    fulfillment: "supermall",
    seller: "dmkcoopic",
    category: "automotive",
    subcategory: null,
    brand: "samsung",
  },
  {
    id: "prod_66",
    name: "Car Phone Mount Wireless Charger 15W Fast Charging",
    image: "https://images.unsplash.com/photo-1618761714954-0b8cd0026356?w=200&h=200&fit=crop",
    price: 129,
    originalPrice: 169,
    currency: "AED",
    fulfillment: "supermall",
    seller: "trizone",
    category: "automotive",
    subcategory: null,
    brand: null,
  },
];

export const partners = [
  { id: "9999", name: "Sample Partner" },
  { id: "1234", name: "Premium Brands Co." },
  { id: "5678", name: "Fashion House" },
  { id: "4321", name: "Tech Distributor" },
  { id: "8765", name: "Beauty Brands Inc." },
];

// Audience targeting options
export const targetingActions = {
  reengagement: [
    { id: "product_page_view", name: "Product Page View" },
    { id: "add_to_cart", name: "Add to Cart" },
    { id: "purchase", name: "Purchase" },
    { id: "wishlist", name: "Add to Wishlist" },
    { id: "search", name: "Search" },
  ],
  demographic: [
    { id: "credit_card", name: "Credit Card" },
    { id: "monthly_spends", name: "Monthly Spends" },
    { id: "loyalty_tier", name: "Loyalty Tier" },
    { id: "account_age", name: "Account Age" },
    { id: "order_frequency", name: "Order Frequency" },
  ],
};

export const targetingFilters = {
  reengagement: {
    category: categories,
    brand: brands,
  },
  demographic: {
    credit_card: [
      { id: "nbd_cobrand", name: "NBD Cobrand" },
      { id: "adcb", name: "ADCB" },
      { id: "fab", name: "FAB" },
      { id: "emirates_nbd", name: "Emirates NBD" },
    ],
    monthly_spends: [
      { id: "top_10", name: "Top 10%" },
      { id: "top_25", name: "Top 25%" },
      { id: "top_50", name: "Top 50%" },
    ],
    loyalty_tier: [
      { id: "gold", name: "Gold" },
      { id: "silver", name: "Silver" },
      { id: "bronze", name: "Bronze" },
    ],
  },
};

export const lookbackOptions = [
  { value: 7, label: "7 Days" },
  { value: 14, label: "14 Days" },
  { value: 30, label: "30 Days" },
  { value: 60, label: "60 Days" },
  { value: 90, label: "90 Days" },
];
